// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlovwaPR8U9dAKOQecm2YUJbALsMUSzqY',
    appId: '1:369310402039:web:ccfcbffb63ba240ae89af2',
    messagingSenderId: '369310402039',
    projectId: 'pharmacy-8cd81',
    authDomain: 'pharmacy-8cd81.firebaseapp.com',
    storageBucket: 'pharmacy-8cd81.appspot.com',
    measurementId: 'G-4KQREJRKWZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAchlrhIfj-gn2_mgvGJCOhQ9if05GCMRc',
    appId: '1:369310402039:android:db556d81a4042f68e89af2',
    messagingSenderId: '369310402039',
    projectId: 'pharmacy-8cd81',
    storageBucket: 'pharmacy-8cd81.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfcMp_W429ObdLzdLe4zI2XHDwvZv6IUo',
    appId: '1:369310402039:ios:ee9034281012db2ce89af2',
    messagingSenderId: '369310402039',
    projectId: 'pharmacy-8cd81',
    storageBucket: 'pharmacy-8cd81.appspot.com',
    iosClientId: '369310402039-qel3to0b72v5vi0n6ugfpepkniteqd29.apps.googleusercontent.com',
    iosBundleId: 'com.example.pharmacy',
  );
}
